---
# 存储
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-loki-ruler-executor-logging-loki-ruler
  namespace: logging-loki-ruler
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /k8slpv/monitor/logging/loki-ruler
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.90.11